# Generated by Django 5.0 on 2024-06-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrsettingmodel',
            name='generate_barcode',
        ),
    ]
