# Generated by Django 5.0 on 2024-06-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_remove_hrsettingmodel_generate_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='state',
        ),
    ]
