# Generated by Django 5.0 on 2024-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_remove_staffmodel_lga_remove_staffmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='mobile',
            field=models.CharField(default='090', max_length=20),
            preserve_default=False,
        ),
    ]
