# Generated by Django 5.0 on 2024-07-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_alter_staffmodel_email_alter_staffmodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='middle_name',
        ),
    ]
