# Generated by Django 5.0 on 2024-09-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('human_resource', '0005_remove_staffmodel_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
