# Generated by Django 5.0 on 2024-06-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIDGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField()),
                ('last_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'SUCCESS'), ('f', 'FAIL')], default='f', max_length=10)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.countrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from_amount', models.FloatField(default=1)),
                ('currency_to_amount', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currencymodel')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to', to='finance.currencymodel')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currencymodel')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currencymodel')),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePaymentPlatformModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('paypal', 'PAYPAL'), ('paystack', 'PAYSTACK'), ('flutterwave', 'Flutterwave')], max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('public_key', models.CharField(max_length=250)),
                ('private_key', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('vat', models.FloatField(default=0.0)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currencymodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('value_in_default_currency', models.FloatField()),
                ('payment_method', models.CharField(choices=[('online', 'ONLINE'), ('offline', 'OFFLINE')], max_length=20)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='finance/fee_payment')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_to_amount', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.cohortmodel')),
            ],
        ),
    ]
