# Generated by Django 5.0 on 2024-06-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('student', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.coursemodel'),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currencymodel'),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='default_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='default_currency', to='finance.currencymodel'),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
