# Generated by Django 5.0 on 2024-06-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymodel',
            name='exchange_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
