# Generated by Django 5.0 on 2024-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_currencymodel_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmodel',
            name='use_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='onlinepaymentplatformmodel',
            name='use_global',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='CurrencyConversionModel',
        ),
    ]
