# Generated by Django 5.0 on 2024-06-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financesettingmodel_auto_confirm_online_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
    ]
