# Generated by Django 5.0 on 2024-06-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_currencymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymodel',
            name='use_global',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
