# Generated by Django 5.0 on 2024-06-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_currencymodel_use_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
