# Generated by Django 5.0 on 2024-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_trainingpaymentmodel_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpaymentmodel',
            name='currency_to_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
