# Generated by Django 5.0 on 2024-06-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_trainingpaymentmodel_currency_to_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpaymentmodel',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='trainingpaymentmodel',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='trainingpaymentmodel',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccountmodel'),
        ),
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingpaymentmodel',
            name='value_in_default_currency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
