# Generated by Django 5.0 on 2024-06-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_financesettingmodel_current_access_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financesettingmodel',
            old_name='current_minimum_payment',
            new_name='minimum_payment',
        ),
    ]
