# Generated by Django 5.0 on 2024-06-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_rename_current_minimum_payment_financesettingmodel_minimum_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentidgeneratormodel',
            name='type',
        ),
    ]
