# Generated by Django 5.0 on 2024-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_remove_paymentidgeneratormodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'COMFIRMED')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='onlinepaymentplatformmodel',
            name='platform',
            field=models.CharField(choices=[('paypal', 'PAYPAL'), ('paystack', 'PAYSTACK')], max_length=50),
        ),
    ]
