# Generated by Django 5.0 on 2024-07-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_trainingpaymentmodel_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingpaymentmodel',
            old_name='value_in_default_currency',
            new_name='value_in_currency',
        ),
    ]
