# Generated by Django 5.0 on 2024-07-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_rename_value_in_default_currency_trainingpaymentmodel_value_in_currency'),
        ('training', '0010_alter_lessonmaterialmodel_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.enrollmentmodel'),
        ),
    ]
