# Generated by Django 5.0 on 2024-07-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_alter_siteinfomodel_facebook_handle_and_more'),
        ('finance', '0019_bankaccountmodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentplatformmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.countrymodel'),
        ),
    ]
