# Generated by Django 5.0 on 2024-07-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_onlinepaymentplatformmodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpaymentmodel',
            name='platform_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
