# Generated by Django 5.0 on 2024-07-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_trainingpaymentmodel_platform_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpaymentmodel',
            name='currency_to_amount',
        ),
        migrations.AlterField(
            model_name='trainingpaymentmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], default='active', max_length=20),
        ),
    ]
