# Generated by Django 5.0 on 2024-07-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_remove_trainingpaymentmodel_currency_to_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountmodel',
            name='use_global',
        ),
    ]
