# Generated by Django 5.0 on 2024-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_bankaccountmodel_use_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymodel',
            name='use_global',
        ),
        migrations.AddField(
            model_name='bankaccountmodel',
            name='use_global',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
