# Generated by Django 5.0 on 2024-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_remove_currencymodel_use_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpaymentmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('declined', 'DECLINED')], default='pending', max_length=20),
        ),
    ]
