# Generated by Django 5.0 on 2024-07-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_studentmessagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessagemodel',
            name='is_replied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
