# Generated by Django 5.0 on 2024-07-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_studentmessagemodel_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmessagemodel',
            name='reply',
        ),
    ]
