# Generated by Django 5.0 on 2024-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohortmodel',
            old_name='expected_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='cohortmodel',
            old_name='expected_start_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='cohortmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Not Commenced'), ('1', 'In Progress'), ('2', 'Concluded')], default='0', max_length=50),
        ),
    ]
