# Generated by Django 5.0 on 2024-06-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_expected_end_date_cohortmodel_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodel',
            name='date_of_birth',
        ),
    ]
