# Generated by Django 5.0 on 2024-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentsmodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortmodel',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cohortmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentsmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10),
        ),
    ]
