# Generated by Django 5.0 on 2024-07-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_student_studentprofilemodel_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodel',
            name='middle_name',
        ),
    ]
