# Generated by Django 5.0 on 2024-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=50)),
                ('mobile_1', models.CharField(max_length=20)),
                ('mobile_2', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(upload_to='images/setting/logo')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='images/setting/logo')),
                ('preloader', models.FileField(blank=True, null=True, upload_to='images/setting/logo')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_handle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
