# Generated by Django 5.0 on 2024-06-07 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_remove_siteinfomodel_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='long_name_code',
            new_name='long_code_name',
        ),
        migrations.RenameField(
            model_name='countrymodel',
            old_name='short_name_code',
            new_name='short_code_name',
        ),
        migrations.AddField(
            model_name='professionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
