# Generated by Django 5.0 on 2024-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_rename_long_name_code_countrymodel_long_code_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfomodel',
            name='facebook_handle',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfomodel',
            name='linkedin_handle',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfomodel',
            name='twitter_handle',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfomodel',
            name='youtube_handle',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
