# Generated by Django 5.0 on 2024-07-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_alter_siteinfomodel_facebook_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfomodel',
            name='primary_color',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfomodel',
            name='secondary_color',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
    ]
