# Generated by Django 4.2.4 on 2024-08-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_siteinfomodel_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='country_code',
            field=models.CharField(max_length=100),
        ),
    ]
