# Generated by Django 5.0 on 2024-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_lessonmaterialmodel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='duration',
            field=models.CharField(default='18 months', max_length=100),
            preserve_default=False,
        ),
    ]
