# Generated by Django 5.0 on 2024-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_coursemodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentmodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
    ]
