# Generated by Django 5.0 on 2024-07-03 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_studentsmodel_middle_name'),
        ('training', '0006_alter_enrollmentmodel_cohort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.cohortmodel'),
        ),
    ]
