# Generated by Django 5.0 on 2024-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_enrollmentmodel_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentmodel',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
