# Generated by Django 5.0 on 2024-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_enrollmentmodel_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmodel',
            options={'ordering': ['course', 'order']},
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
