# Generated by Django 5.0 on 2024-07-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_lessonmodel_options_lessonmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmaterialmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='training.lessonmodel'),
        ),
    ]
