# Generated by Django 5.0 on 2024-07-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_livesessionmodel_delete_livesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesessionmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='training.coursemodel'),
        ),
    ]
