# Generated by Django 5.0 on 2024-07-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_livesessionmodel_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesessionmodel',
            name='trainers',
        ),
    ]
