# Generated by Django 5.0 on 2024-07-09 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_studentsmodel_middle_name'),
        ('training', '0014_alter_livesessionmodel_join_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracking',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.cohortmodel'),
        ),
        migrations.AlterField(
            model_name='progresstracking',
            name='progress',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
