# Generated by Django 5.0 on 2024-07-09 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_studentsmodel_middle_name'),
        ('training', '0015_progresstracking_cohort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.JSONField(blank=True, null=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.cohortmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='student.studentsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgressTracking',
        ),
    ]
