# Generated by Django 4.2.4 on 2024-08-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_alter_progressmodel_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressmodel',
            name='progress',
            field=models.JSONField(default={}),
        ),
    ]
